In [14]:
import numpy as np
import math
import random
from PIL import Image


Excercise 1 --- Check if a number is prime. 

In [15]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

num = int(input("Enter a number: "))
print("This is a prime number" if is_prime(num) else "This is not a prime number")

This is a prime number


Excercise 2 --- Fibonacci sequence.

In [ ]:
n = int(input("Enter the number of Fibonacci terms: "))
a, b = 0, 1
for _ in range(n):
    print(a, end=" ")
    a, b = b, a + b
print()

Excercise 3 --- Print decreasing triangle pattern.

In [16]:
rows = 5
for i in range(rows, 0, -1):
    print("* " * i)


* * * * * 
* * * * 
* * * 
* * 
* 


Excercise 4 --- Reverse a string.

In [18]:
def reverse_string():
    s = input("Enter a string: ")
    print("Reversed string:", s[::-1])
reverse_string()

Reversed string: olleh


Excercise 5 --- Min and max function.

In [21]:
def find_min_max(iterable):
    return min(iterable), max(iterable)

Excercise 6 --- Guess the number.

In [22]:
target = random.randint(1, 10)
while True:
    guess = int(input("Guess a number (1-10): "))
    if guess < target:
        print("Too low! Try again.")
    elif guess > target:
        print("Too high! Try again.")
    else:
        print("Correct! You win!")
        break

Too low! Try again.
Correct! You win!


Excercise 7 --- Password checker.

In [23]:
correct_password = "Python123"
while True:
    password = input("Enter password: ")
    if password == correct_password:
        print("Access Granted!")
        break
    else:
        print("Incorrect password. Try again.")

Incorrect password. Try again.
Incorrect password. Try again.
Access Granted!


Excercise 8 --- Series calculation.

In [29]:
def series_sum(x, N):
    total = 0
    for i in range(1, N+1):
        total += x * (5**i)**2 / (i + math.factorial(i+1))
    return total

x = float(input("Enter x: "))
N = int(input("Enter N: "))
print("Series result:", series_sum(x, N))

Series result: 432.2916666666667


Excercise 9 --- Image manipulation

In [30]:
img = Image.open("your_image.jpg")
img_array = np.array(img)
horizontal_flip = np.fliplr(img_array)
vertical_flip = np.flipud(img_array)
Image.fromarray(horizontal_flip).show()
Image.fromarray(vertical_flip).show()

FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/m3289-210775-Part-1-Submission/jupyter_notebook/your_image.jpg'

Excercise 10 --- Temperature analysis.

In [31]:
temps = np.array([22, 24, 19, 21, 23, 25, 26, 27, 24, 23, 20, 22, 21, 19, 18, 22, 23, 24, 26, 28, 30, 27, 25, 26, 24, 22, 21, 20, 19, 23])
print("Min Temp:", np.min(temps))
print("Max Temp:", np.max(temps))
print("Avg Temp:", np.mean(temps))
temps_fahrenheit = temps * 9/5 + 32
print("Temperatures in Fahrenheit:", temps_fahrenheit)
print("Days above 25°C:", temps[temps > 25])
print("Days below 20°C:", np.sum(temps < 20))
print("Sorted temperatures:", np.sort(temps))
temps_reshaped = temps.reshape(5, 6)
print("Reshaped array:")
print(temps_reshaped)

Min Temp: 18
Max Temp: 30
Avg Temp: 23.133333333333333
Temperatures in Fahrenheit: [71.6 75.2 66.2 69.8 73.4 77.  78.8 80.6 75.2 73.4 68.  71.6 69.8 66.2
 64.4 71.6 73.4 75.2 78.8 82.4 86.  80.6 77.  78.8 75.2 71.6 69.8 68.
 66.2 73.4]
Days above 25°C: [26 27 26 28 30 27 26]
Days below 20°C: 4
Sorted temperatures: [18 19 19 19 20 20 21 21 21 22 22 22 22 23 23 23 23 24 24 24 24 25 25 26
 26 26 27 27 28 30]
Reshaped array:
[[22 24 19 21 23 25]
 [26 27 24 23 20 22]
 [21 19 18 22 23 24]
 [26 28 30 27 25 26]
 [24 22 21 20 19 23]]
